syntax = "proto3";

option csharp_namespace = "GreeterServiceApp";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}

//syntax = "proto3"; 

//option csharp_namespace = "GreeterServiceApp"; 

//package greet; 

//// service definition 
//service Greeter { 
//  // sending a message 
//  rpc SayHello (HelloRequest) returns (HelloReply); 
//} 

//// the message from the client contains the name 
//message HelloRequest { 
//  string name = 1; 
//} 

//// the message to the client contains the message 
//message HelloReply { 
//  string message = 1; 
//} 